=== DoraVolz/COMP2150_DoraVolz/XML_JSONAssignment/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://sascs.net/sascs/instructors"
xmlns:i="http://sascs.net/sascs/instructors"
elementFormDefault="qualified">

<xs:element name="instructors">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="instructor" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="city" type="xs:string"/>
                        <xs:element name="state" type="xs:string"/>
                        <xs:element name="phone" type="xs:string"/>
                        <xs:element name="certification" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== DoraVolz/COMP2150_DoraVolz/XML_JSONAssignment/instructors.xml
<?xml version = "1.0"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>
<i:instructors
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://sascs.net/sascs/instructors schema.xsd"
xmlns:i="http://sascs.net/sascs/instructors">
    <i:instructor id="JV1000">
        <i:name>Jack Volz</i:name>
        <i:city>Minnesota Lake</i:city>
        <i:state>MN</i:state>
        <i:phone>507-123-8777</i:phone>
        <i:certification>FFI, FFII, EMS, and HAZMAT</i:certification>
    </i:instructor>
    <i:instructor id="MS1001">
        <i:name>Matt Santo</i:name>
        <i:city>Jansville</i:city>
        <i:state>MN</i:state>
        <i:phone>380-123-9898</i:phone>
        <i:certification>FFI, FFII, and HAZMAT</i:certification>
    </i:instructor>
    <i:instructor id="SS1002">
        <i:name>Sam Smith</i:name>
        <i:city>Sioux Falls</i:city>
        <i:state>SD</i:state>
        <i:phone>623-656-1243</i:phone>
        <i:certification>FFI and FFII</i:certification>
    </i:instructor>
</i:instructors>
